export const ShirtType=['color','colar','Cuff',"Pocket","contrast","mono","Bottom","Front","Back","Review"]

export const Whatsapp= require("../../assets/whatsapp.png")

export const DRESSES = [
  {
    id: 1,
    imageUri: require("../../assets/shirt/black1.jpeg"),
    name: "Helena",
    priceOne: 120,
    priceTwo: "$180",
    color: "black",
  },
  {
    id: 2,
    imageUri: require("../../assets/shirt/black2.jpeg"),
    name: "Helena",
    priceOne: 120,
    priceTwo: "$180",
    color: "black",
  },
  {
    id: 3,
    imageUri: require("../../assets/shirt/black3.jpeg"),
    name: "Helena",
    priceOne: 120,
    priceTwo: "$180",
    color: "black",
  },
  {
    id: 4,
    imageUri: require("../../assets/shirt/black4.jpeg"),
    name: "Helena",
    priceOne: 120,
    priceTwo: "$180",
    color: "black",
  },
  {
    id: 5,
    imageUri: require("../../assets/shirt/black5.jpeg"),
    name: "Helena",
    priceOne: 120,
    priceTwo: "$180",
    color: "black",
  },
  {
    id: 6,
    imageUri: require("../../assets/shirt/yellow1.jpeg"),
    name: "Marie-Anne short",
    priceOne: 180,
    priceTwo: null,
    color: "yellow",
  },
  {
    id: 7,
    imageUri: require("../../assets/shirt/yellow2.jpeg"),
    name: "Marie-Anne short",
    priceOne: 180,
    priceTwo: null,
    color: "yellow",
  },
  {
    id: 8,
    imageUri: require("../../assets/shirt/yellow3.jpeg"),
    name: "Marie-Anne short",
    priceOne: 180,
    priceTwo: null,
    color: "yellow",
  },
  {
    id: 9,
    imageUri: require("../../assets/shirt/yellow4.jpeg"),
    name: "Marie-Anne short",
    priceOne: 180,
    priceTwo: null,
    color: "yellow",
  },
  {
    id: 10,
    imageUri: require("../../assets/shirt/yellow5.jpeg"),
    name: "Marie-Anne short",
    priceOne: 180,
    priceTwo: null,
    color: "yellow",
  },

  {
    id: 11,
    imageUri: require("../../assets/shirt/green1.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "green",
  },
  {
    id: 12,
    imageUri: require("../../assets/shirt/green2.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "green",
  },
  {
    id: 13,
    imageUri: require("../../assets/shirt/green3.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "green",
  },
  {
    id: 14,
    imageUri: require("../../assets/shirt/green4.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "green",
  },
  {
    id: 15,
    imageUri: require("../../assets/shirt/green5.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "green",
  },
  {
    id: 16,
    imageUri: require("../../assets/shirt/green6.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "green",
  },
  {
    id: 17,
    imageUri: require("../../assets/shirt/blue1.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "blue",
  },
  {
    id: 18,
    imageUri: require("../../assets/shirt/blue2.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "blue",
  },
  {
    id: 19,
    imageUri: require("../../assets/shirt/blue3.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "blue",
  },
  {
    id: 20,
    imageUri: require("../../assets/shirt/blue4.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "blue",
  },
  {
    id: 21,
    imageUri: require("../../assets/shirt/blue5.jpeg"),
    name: "Betruschka",
    priceOne: 80,
    priceTwo: null,
    color: "blue",
  },
];
